### ISSUE TITLE
Problems merging i get an error message

### ISSUE THREAD

**Issue by bpatinojw** [AndreasSko/ios-jwlm#69] opened 2023-08-29 17:18 UTC
schema version is too new. Should be 13 is 14. Make sure you use the latest version of the merger

**Comment by sircharlo** [comment] 2023-09-01 11:42
Duplicate of #68

**Comment by AndreasSko** [comment] 2023-09-01 17:56
Thank you for reporting this issue. I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄

**Closed by AndreasSko** 2023-09-01 17:56 UTC

**Comment by bpatinojw** [comment] 2023-09-01 22:36
Thank you!


On Sep 1, 2023, at 12:56 PM, Andreas Skorczyk ***@***.***> wrote:


Thank you for reporting this issue. I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄
