### ISSUE TITLE
Merging failure 

### ISSUE THREAD

**Issue by Punjabi2018** [AndreasSko/ios-jwlm#70] opened 2023-08-31 14:59 UTC
I have IOS 16.3.1, my merger app and publication catalogue is up to date and I am using JWL 14.0.2
When I try to select a back up , I receive this message:
« schema version is too new. Should be 13 is 14. Make sure you use the latest version of the merger« 
Is it that the current Merger version is not up to date with JWL 14? 
thank you for you help. This app is absolutely amazing and have been so useful! Keep on the good work 🙏🏽!

**Comment by sircharlo** [comment] 2023-09-01 11:43
Duplicate of #68

**Comment by AndreasSko** [comment] 2023-09-01 17:56
Thank you for reporting this issue and your kind words 🙂 
I just submitted an update to the App Store which adds support for the new backup version. You should hopefully be able to download it within the next couple of days 👍😄

**Closed by AndreasSko** 2023-09-01 17:56 UTC
